apiVersion: v1
kind: Pod
metadata:
   name: ubuntu02
lables: 
   environment: dev
   app: ubuntu01-dev
spec:
   container: 
    - name: ubuntu01
      image: ubuntu:16.04
   ports:
      - containerports: 8080